### ISSUE TITLE
Feature Request - Add maxSurge for blockscout deployment

### ISSUE THREAD

**Issue by mario-sangar** [blockscout/helm-charts#20]
The `maxSurge` setting is needed for the indexer side, so only one replica is up when rolling updates to the deployment.

**Comment by nzenchik** [comment]
We haven't done this because usually it is okay to have two indexer pods during update(for 2-3 mins). The only situation when it doesn't work is some major updates when migrations cannot start because of another indexer pod. But this occurs rarely so in this case we suggest to scale deployment to 0 and run update. 
If we add maxSurge this will cause downtime during all backend updates.
